Import java.util.Scanner
public class control {
    pubic static void main(string[] args) {
int a=integer.parseInt(args[0]);
int b=integer.parseInt(args[1]);
int c=integer.parseInt(args[2]);
if(a>b && a>c) {
    System.out.println("a is greater");
    }else if(b>a && b>c) {
        System.out.println("b is greater");
        }else if(c>a && c>b) {
            System.out.println("c is greater");
    }
}
}

